Layout/IndentationWidth:
  Width: 4

Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Style/GuardClause:
  Enabled: false
